spring:
  application:
    name: "server"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "${CODCHI_POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
